backend:
  name: git-gateway
  branch: main
media_folder: static/images/uploads
public_folder: /images/uploads
collections:
  - name: chapter
    label: Chapter
    folder: content/chapter
    create: true
    slug: '{{slug}}'
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Chapter Number", name: "chapter_number", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
