backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
    - name: "upanyas"
    label: "महामाया के Chapters"
    folder: "chapters"
    create: true
    slug: "{{title}}-{{slug}}"
    fields:
            - {label: "Upanyas Ka Naam", name: "title", widget: "string"}
            - {label: "Bhasha", name: "bhasha", widget: "select", options: ["Hindi", "Hinglish", "Sanskrit", "Pahadi", "Bhojpuri", "English"]}
            - {label: "Chapter Number", name: "chapter", widget: "string"}
            - {label: "Chapter Likho", name: "body", widget: "markdown"}
